# About Dataset

This dataset contains information about used cars.
This data can be used for a lot of purposes such as price prediction to exemplify the use of linear regression in Machine Learning.

The columns in the given dataset are as follows:

1. Car_Name
2. Year
3. Selling_Price
4. Present_Price
5. Kms_Driven
6. Fuel_Type
7. Seller_Type
8. Transmission
9. Owner

Link to download the Dataset : https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho/data

# Exploration and Data Loading

Importing Dependencies

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Loading Data

In [ ]:
data = pd.read_csv("path/to/your/data.csv")

Inspecting the first 5 rows of the dataframe

In [4]:
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0


Checking the number of rows and columns

In [5]:
data.shape

(301, 9)

Getting some Information about the data

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [7]:
data.describe()

,Year,Selling_Price,Present_Price,Kms_Driven,Owner
count,301.000000,301.000000,301.000000,301.000000,301.000000
mean,2013.627907,4.661296,7.628472,36947.205980,0.043189
std,2.891554,5.082812,8.644115,38886.883882,0.247915
min,2003.000000,0.100000,0.320000,500.000000,0.000000
25%,2012.000000,0.900000,1.200000,15000.000000,0.000000
50%,2014.000000,3.600000,6.400000,32000.000000,0.000000
75%,2016.000000,6.000000,9.900000,48767.000000,0.000000
max,2018.000000,35.000000,92.600000,500000.000000,3.000000


Checking for Missing values

In [8]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

Checking for the distribution of categorical data

In [10]:
print(data.Fuel_Type.value_counts())
print(data.Seller_Type.value_counts())
print(data.Transmission.value_counts())

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64
Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64
Transmission
Manual       261
Automatic     40
Name: count, dtype: int64


- based on the exploration we can see that most categorical variables have between 2 and 3 categories
- So let's just replace by 0, 1, 2

# Encoding Catogorical Data

We use ONE HOT ENCODING to Encode Catogorical Data

In [11]:
data = pd.get_dummies(data, columns=["Fuel_Type", "Seller_Type", "Transmission"],drop_first=True)


# Splitting Data

We don't need "Car_Name" column, so removing it.

In [12]:
data = data.drop(['Car_Name'], axis=1)

Splitting the Data and target

In [13]:
x = data.drop(['Selling_Price'], axis=1)
y = data['Selling_Price']

In [14]:
x.head()

,Year,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,5.59,27000,0,False,True,False,True
1,2013,9.54,43000,0,True,False,False,True
2,2017,9.85,6900,0,False,True,False,True
3,2011,4.15,5200,0,False,True,False,True
4,2014,6.87,42450,0,True,False,False,True


In [15]:
y.head()

0    3.35
1    4.75
2    7.25
3    2.85
4    4.60
Name: Selling_Price, dtype: float64

Splitting Data and Target into Training and Testing data

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 2)

In [17]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(270, 8) (31, 8) (270,) (31,)


# Machine Learning

# 1. Linear Regression

In [18]:
from sklearn.linear_model import LinearRegression

lin_model = LinearRegression()

Loading the Traing Data into the model

In [19]:
lin_model.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


 Report on Traning

In [20]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

lin_train_pred = lin_model.predict(x_train)

print(f"R-squared : {r2_score(y_train, lin_train_pred):.3f}")
print(f"Mean Absolute Error : {mean_absolute_error(y_train, lin_train_pred):.3f}")
print(f"Mean Squared Error : {mean_squared_error(y_train, lin_train_pred):.3f}")

R-squared : 0.883
Mean Absolute Error : 1.210
Mean Squared Error : 3.185


Report on Testing

In [21]:
lin_test_pred = lin_model.predict(x_test)

print(f"R-squared : {r2_score(y_test, lin_test_pred):.3f}")
print(f"Mean Absolute Error : {mean_absolute_error(y_test, lin_test_pred):.3f}")
print(f"Mean Squared Error : {mean_squared_error(y_test, lin_test_pred):.3f}")

R-squared : 0.869
Mean Absolute Error : 1.073
Mean Squared Error : 1.719


In [22]:
import numpy as np

print(f"RMSE (Train): {np.sqrt(mean_squared_error(y_train, lin_train_pred)):.3f}")
print(f"RMSE (Test) : {np.sqrt(mean_squared_error(y_test, lin_test_pred)):.3f}")

RMSE (Train): 1.785
RMSE (Test) : 1.311


Residual Analysis (Quick Check)

In [23]:
lin_train_residuals = y_train - lin_train_pred
lin_test_residuals = y_test - lin_test_pred

print("Mean Train Residual:", np.mean(lin_train_residuals))
print("Mean Test Residual :", np.mean(lin_test_residuals))

Mean Train Residual: 1.4925344910605216e-13
Mean Test Residual : -0.2516870433753486


**Conclusion on Linear Regression**

• Linear Regression shows good baseline performance with an R² of 0.88 (train) and 0.86 (test).

• Error metrics (MAE ≈ 1.07, RMSE ≈ 1.31 on test data) indicate moderate prediction accuracy.

• Training and test results are reasonably close, suggesting low overfitting.

• Residual means are close to zero, indicating the model is largely unbiased.

# 2. Lasso Regression

In [24]:
from sklearn.linear_model import Lasso

las_model = Lasso()

Loading the Traing data into model

In [25]:
las_model.fit(x_train, y_train)

,"alpha alpha: float, default=1.0Constant that multiplies the L1 term, controlling regularizationstrength. `alpha` must be a non-negative float i.e. in `[0, inf)`.When `alpha = 0`, the objective is equivalent to ordinary leastsquares, solved by the :class:`LinearRegression` object. For numericalreasons, using `alpha = 0` with the `Lasso` object is not advised.Instead, you should use the :class:`LinearRegression` object.",1.0
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"precompute precompute: bool or array-like of shape (n_features, n_features), default=FalseWhether to use a precomputed Gram matrix to speed upcalculations. The Gram matrix can also be passed as argument.For sparse input this option is always ``False`` to preserve sparsity.",False
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``, see Notes below.",0.0001
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fit asinitialization, otherwise, just erase the previous solution.See :term:`the Glossary `.",False
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.",False
,"random_state random_state: int, RandomState instance, default=NoneThe seed of the pseudo random number generator that selects a randomfeature to update. Used when ``selection`` == 'random'.Pass an int for reproducible output across multiple function calls.See :term:`Glossary `.",None
,"selection selection: {'cyclic', 'random'}, default='cyclic'If set to 'random', a random coefficient is updated every iterationrather than looping over features sequentially by default. This(setting to 'random') often leads to significantly faster convergenceespecially when tol is higher than 1e-4.",'cyclic'


Report on Training

In [26]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

las_train_pred = las_model.predict(x_train)

print(f"R-squared : {r2_score(y_train, las_train_pred):.3f}")
print(f"Mean Absolute Error : {mean_absolute_error(y_train, las_train_pred):.3f}")
print(f"Mean Squared Error : {mean_squared_error(y_train, las_train_pred):.3f}")

R-squared : 0.843
Mean Absolute Error : 1.286
Mean Squared Error : 4.268


Report on Test

In [27]:
las_test_pred = las_model.predict(x_test)

print(f"R-squared : {r2_score(y_test, las_test_pred):.3f}")
print(f"Mean Absolute Error : {mean_absolute_error(y_test, las_test_pred):.3f}")
print(f"Mean Squared Error : {mean_squared_error(y_test, las_test_pred):.3f}")

R-squared : 0.871
Mean Absolute Error : 1.051
Mean Squared Error : 1.698


RMSE

In [28]:
import numpy as np

print(f"RMSE (Train): {np.sqrt(mean_squared_error(y_train, las_train_pred)):.3f}")
print(f"RMSE (Test) : {np.sqrt(mean_squared_error(y_test, las_test_pred)):.3f}")

RMSE (Train): 2.066
RMSE (Test) : 1.303


Residual Analysis (Qucik Check)

In [29]:
las_train_residuals = y_train - las_train_pred
las_test_residuals = y_test - las_test_pred

print("Mean Train Residual:", np.mean(las_train_residuals))
print("Mean Test Residual :", np.mean(las_test_residuals))


Mean Train Residual: 6.293566491001036e-14
Mean Test Residual : -0.08027026939691595


**Conclusion on Lasso Regression**

• The Lasso model achieves good predictive performance with R² = 0.84 on training data and 0.87 on test data, indicating strong generalization.

• Lower MAE and MSE on test data show improved prediction accuracy on unseen car prices.

• Residuals are mostly centered around zero, suggesting minimal prediction bias, with a few outliers at higher predicted values.

# 3. Random Forest Regression


In [30]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

Loading Training Data into the model

In [31]:
rf_model.fit(x_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""squared_error"", ""absolute_error"", ""friedman_mse"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""friedman_mse"", which usesmean squared error with Friedman's improvement score for potentialsplits, ""absolute_error"" for the mean absolute error, which minimizesthe L1 loss using the median of each terminal node, and ""poisson"" whichuses reduction in Poisson deviance to find splits.Training using ""absolute_error"" is significantly slowerthan when using ""squared_error""... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 1.0 Poisson criterion.",'squared_error'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=1.0The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None or 1.0, then `max_features=n_features`... note:: The default of 1.0 is equivalent to bagged trees and more randomness can be achieved by setting smaller values, e.g. 0.3... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to 1.0.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",1.0
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsample

Report on Training

In [32]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

rf_train_pred = rf_model.predict(x_train)

print(f"R-squared : {r2_score(y_train, rf_train_pred):.3f}")
print(f"MAE       : {mean_absolute_error(y_train, rf_train_pred):.3f}")
print(f"MSE       : {mean_squared_error(y_train, rf_train_pred):.3f}")

R-squared : 0.986
MAE       : 0.242
MSE       : 0.374


Report on Testing

In [33]:
rf_test_pred = rf_model.predict(x_test)

print(f"R-squared : {r2_score(y_test, rf_test_pred):.3f}")
print(f"MAE       : {mean_absolute_error(y_test, rf_test_pred):.3f}")
print(f"MSE       : {mean_squared_error(y_test, rf_test_pred):.3f}")

R-squared : 0.981
MAE       : 0.334
MSE       : 0.245


In [34]:
import numpy as np

print(f"RMSE (Train): {np.sqrt(mean_squared_error(y_train, rf_train_pred)):.3f}")
print(f"RMSE (Test) : {np.sqrt(mean_squared_error(y_test, rf_test_pred)):.3f}")


RMSE (Train): 0.612
RMSE (Test) : 0.495


Residual Analysis Quick Check

In [35]:
rf_train_residuals = y_train - rf_train_pred
rf_test_residuals = y_test - rf_test_pred

print("Mean Train Residual:", np.mean(rf_train_residuals))
print("Mean Test Residual :", np.mean(rf_test_residuals))


Mean Train Residual: 0.05620407407407413
Mean Test Residual : 0.12191935483871019


**Conclusion on Random Forest Regressor**

• The model shows excellent performance with very high R² scores (0.98 on training and 0.98 on test data), indicating strong predictive power.

• Very low MAE, MSE, and RMSE values demonstrate highly accurate car price predictions.

• Training and test results are very close, suggesting minimal overfitting and strong generalization.

• Mean residuals are close to zero, indicating the model is largely unbiased in its predictions.

# Final Conclusion: Which model to select?

Random Forest was selected as the final model because

• Superior Precision: It reduces the average error (MAE) by approximately 69% compared to the linear models.

• High Explained Variance: It captures 98% of the data's behavior, whereas the linear models miss about 13% of the underlying patterns.

• Non-Linearity: The massive improvement in $R^2$ suggests that the relationship between your features and the target variable is likely non-linear, which the Random Forest handles naturally, while the linear models struggle.

• Stability: Despite being a complex ensemble model, the test results remain incredibly close to the training results, proving it is a reliable and stable predictor.